### ISSUE TITLE
psycopg2.DataError: invalid input syntax for type timestamp: ""

### ISSUE THREAD

**Issue by klonuo** [biolab/orange3#1351]
This happens anytime I add date field in "Select Rows" condition. So it seems like a bad flow, as it happens just by selecting datetime variable, w/o selecting operator and value. After this exception I can select operator and add a value to get filtered data that seem fine.

```pytb
--------------------------------------------------------------------------------
DataError                                     Traceback (most recent call last):
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\data\owselectrows.py", line 136, in <lambda>
    lambda _: self.set_new_operators(attr_combo, False))
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\data\owselectrows.py", line 170, in set_new_operators
    self.set_new_values(oper_combo, adding_all, selected_values)
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\data\owselectrows.py", line 285, in set_new_values
    self.conditions_changed()
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\data\owselectrows.py", line 329, in conditions_changed
    self.commit()
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\gui.py", line 2183, in unconditional_commit
    do_commit()
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\gui.py", line 2191, in do_commit
    commit()
  File "D:\Python\x32\Python34\lib\site-packages\Orange\widgets\data\owselectrows.py", line 408, in commit
    self.match_desc = report.describe_data_brief(matching_output)
  File "D:\Python\x32\Python34\lib\site-packages\Orange\canvas\report\report.py", line 650, in describe_data_brief
    items["Data instances"] = data.approx_len()
  File "D:\Python\x32\Python34\lib\site-packages\Orange\data\sql\table.py", line 317, in approx_len
    with self._execute_sql_query(sql) as cur:
  File "D:\Python\x32\Python34\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "D:\Python\x32\Python34\lib\site-packages\Orange\data\sql\table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.DataError: invalid input syntax for type timestamp: ""
LINE 1: ...aba','polutant_NO2','polutant_CO','polutant_PM10') AND "datum" = ''
```

Using latest Orange 3.3

**Comment by lanzagar** [comment]
Thank you for reporting this. Currently date fields are mapped to python StringVariable and the default value for that is '' (empty string), but date columns in the database cannot be compared to that.

Orange has received a TimeVariable type recently, which would be the right mapping - so this should be handled much better (and without the error) quite soon.
Until then, you can avoid the annoying error message by unchecking the Send automatically option in Select Rows and making sure that the operator and value are valid before clicking Send manually.

**Comment by lanzagar** [comment]
"quite soon" took a while, but PRs #1424 and #1429 (along with #1430 for similar cases) should fix this.

Please see if it works for you too.

**Comment by klonuo** [comment]
Hi @lanzagar, thanks for your replies

I just tested with latest binary (3.3.6 rev.ee294bc), but the issue still remains - I get exact error.

**Comment by ajdapretnar** [comment]
@klonuo 3.3.6 rev.ee294bc is only the official release. The fixes haven't yet been released, so I suggest you to check the very latest version from Github in order to see whether this works. If you don't want to mess with Git, you can wait until Friday, when we'll hopefully going to release version 3.3.7.

**Comment by astaric** [comment]
Or try the latest nightly build from http://orange.biolab.si/download/files/nightly/

**Comment by klonuo** [comment]
Thanks guys :)

I don't mind git and compiling, but I use Python 3.5 (not very big difference but still if it's targeted for 3.4) and installer is very solid from my experience.

Nice to know about nightly builds. However I'll wait for Friday as latest nightly is still to late for those commits referenced.

**Comment by ajdapretnar** [comment]
Closed via #1424, #1429 and #1430.
