### ISSUE TITLE
Test & Score Widget

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3#2435]
##### Orange version

Orange3 3.4.4

##### Expected behavior
Evaluation Results in Test & Score

##### Actual behavior
Evaluation Results in Test & Score Not Calculated

##### Steps to reproduce the behavior
Run Schema

##### Additional info (worksheets, data, screenshots, ...)
titanic.tab used in model

**Comment by ajdapretnar** [comment]
@Norsusan Thank you for reporting this! We have just discovered the results are indeed calculated, but defaults are not set for display. If you go to Evaluation Results header and use the right click, you should be able to add custom columns for ER. It's not ideal, but it will solve the issue until we fix it properly.

<img width="842" alt="screen shot 2017-06-27 at 12 26 40" src="https://user-images.githubusercontent.com/12524972/27583205-eb5d6e9e-5b33-11e7-97fa-fefc7a1e486b.png">

**Comment by Norsusan** [comment]
Hello,

 

Also please check out ROC Analysis as not working. (Could be part of same problem as in Test & Score)

 

Thank you,

 

Norm

 

Norman Abraham CFP

Tel: (613) 261-0947

Email:  <mailto:norman.abraham@teksavvy.com> norman.abraham@teksavvy.com

              <mailto:risk.analytics@teksavvy.com> risk.analytics@teksavvy.com

Web:   <http://www.riskanalytics.ca/> www.RiskAnalytics.ca

“Think Outside The Box”

**Comment by janezd** [comment]
The first issue will be solved #2437.

In the future, please report separate issues separately.

**Comment by ajdapretnar** [comment]
ROC Analysis works for me. As @janezd suggested, perhaps you can open another issue and describe the steps to reproduce.

**Comment by Norsusan** [comment]
Hi Ajda,

 

Not quite sure where to right click on Evaluation Results to manually add custom columns.

 

Perhaps when I figure it out the ROC Analysis will be fixed.

 

Thank you for your help.

 

Norm

 

Norman Abraham CFP

Tel: (613) 261-0947

Email:  <mailto:norman.abraham@teksavvy.com> norman.abraham@teksavvy.com

              <mailto:risk.analytics@teksavvy.com> risk.analytics@teksavvy.com

Web:   <http://www.riskanalytics.ca/> www.RiskAnalytics.ca

“Think Outside The Box”

**Comment by ajdapretnar** [comment]
In the header. Next to 'Method'.

**Comment by Norsusan** [comment]
Thank you

 

Norman Abraham CFP

Tel: (613) 261-0947

Email:  <mailto:norman.abraham@teksavvy.com> norman.abraham@teksavvy.com

              <mailto:risk.analytics@teksavvy.com> risk.analytics@teksavvy.com

Web:   <http://www.riskanalytics.ca/> www.RiskAnalytics.ca

“Think Outside The Box”

**Comment by ajdapretnar** [comment]
p.s. If you reply via e-mail, Github seems to report the entire correspondence, which is a slightly undesired effect (reports your phone number + it makes everything quite difficult to read). Perhaps it might be a good idea to edit the reply beforehand.

**Comment by janezd** [comment]
Fixed in #2437.

**Comment by divyaer** [comment]
Hi, 
Orange version : 3.16. The issue still persists, I am unable to view the Test and Score results:
![image](https://user-images.githubusercontent.com/43588455/46043482-c5c13080-c135-11e8-97ac-645d455d7b75.png)

**Comment by ajdapretnar** [comment]
@divyaer I assume your workflow is not entirely right. I cannot see how you can even select Cross validation by feature without having any metas. Could you perhaps post the entire workflow?

**Comment by divyaer** [comment]
You are absolutely right, apologies for posting the query here. I am a novice, trying to learn to work with Orange. Thanks for your response.

**Comment by ajdapretnar** [comment]
No problem! I would recommend watching our [video tutorials](https://www.youtube.com/playlist?list=PLmNPvQr9Tf-ZSDLwOzxpvY-HrE0yv-8Fy&disable_polymer=true) that explain the basic procedures in Orange.

**Comment by divyaer** [comment]
Sure... I must!
