### ISSUE TITLE
Saving images as PDF does not work as it should

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2887]
##### Orange version
All versions tested since 3.4.2. (3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.9, 3.10).

##### Expected behavior
WYSIWYG

##### Actual behavior
![screenshot_20180125_103312](https://user-images.githubusercontent.com/22157215/35381003-3003d8fc-01bb-11e8-9386-e63504bc53e8.png)
![screenshot_20180125_103306](https://user-images.githubusercontent.com/22157215/35381007-33dbb9cc-01bb-11e8-803c-8d1f69be954e.png)

##### Additional info (worksheets, data, screenshots, ...)
PDF was introduced in #2210 . See also ##2108 .

**Comment by markotoplak** [comment]
Pdf export in Orange works as first exporting svg and then converting it to pdf.

This was partly fixed in #2930 (for svg export part), but then svg->pdf conversion still has problems on the edges.

![screen shot 2018-06-06 at 10 06 21](https://user-images.githubusercontent.com/552182/41025101-58cd12ee-6971-11e8-8a6d-ac454d093a24.png)
![screen shot 2018-06-06 at 10 08 56](https://user-images.githubusercontent.com/552182/41025247-ad047866-6971-11e8-87c1-b54b31dc5cad.png)

**Comment by ajdapretnar** [comment]
The problem persists and it is very annoying. Any ideas how to solve this? If one can't see axes names, what is the point of saving visualization? 🙈

**Comment by lanzagar** [comment]
This seems to be working fine now for me on master (3.20).
Can we close this?

**Comment by markotoplak** [comment]
@lanzagar, which Qt version do you have?

**Comment by lanzagar** [comment]
Qt 5.12.2
And maybe "working fine" was a bit misleading. I don't have the big problems mentioned in this issue: points are points (not rgb triplets) and  I see axis labels :)
The figure is still not as nice as the png version... the points are "fatter" with thicker outlines, the axis ticks are not the same as in the visualization etc.
But although not perfect, it looks acceptable.

[iris.pdf](https://github.com/biolab/orange3/files/2988087/iris.pdf)

![iris](https://user-images.githubusercontent.com/4579717/54683813-eda4b600-4b12-11e9-8f4f-659b2ea48cbc.png)
