### ISSUE TITLE
Slow scrolling QTableViews (Distance Matrix, Data Table, Predictions)

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#5073]
#### The problem

Scrolling in QTableViews is unnecessarily laggy.

#### Some info

This is something we've talked about, and I did some digging, I thought I should document it in an issue.

Attaching this code block to `CanvasApplication` allows one to profile some Qt stuff:
```python
t = QElapsedTimer()

    def notify(self, receiver, event):
        self.t.start()
        ret = QApplication.notify(self, receiver, event)
        if self.t.elapsed() > 10:
            print(f"processing event type {event.type()} for object {receiver.objectName()} "
                  f"took {self.t.elapsed()}ms")
        return ret
```

When scrolling Distance Matrix, these events pop up like crazy:
```
processing event type 12 for object qt_scrollarea_viewport took 29ms
processing event type 12 for object qt_scrollarea_viewport took 30ms
processing event type 12 for object qt_scrollarea_viewport took 31ms
```

Event type 12 is paint, and it invokes `Orange.widgets.unsupervised.owdistancematrix.DistanceMatrixModel.data` (`Orange/widgets/unsupervised/owdistancematrix.py:72`) a LOT. Making the window larger increases the time taken. It seems that on every little scroll, all of the information in the model is queried again, for each role (even those not defined in the `data()` method). 

<!--
When connecting distances to Distance Matrix, it takes a while to start up, hanging on `PyQt5.QtCore.QAbstractItemModel.QAbstractItemModel.endResetModel` (`Orange/widgets/unsupervised/owdistancematrix.py:43`). 

A Qt forum answer suggests that beginResetModel and endResetModel should be replaced by insertions/removals of rows/columns. https://forum.qt.io/topic/50825/qsortfilterproxy-slow/4
A SO answer suggests implementing something similar to QTreeView's setUniformRowHeights. https://stackoverflow.com/questions/50943356/qtableview-performance
--<

**Comment by janezd** [comment]
I believe the problem with Distance Matrix is now fixed (#5136).

**Comment by irgolic** [comment]
Partly, yes, as I understand it, Diatance Matrix no longer takes ages to start up? This issue was primarily opened for the slow scrolling in QTableViews, still present in Distance Matrix.

**Comment by janezd** [comment]
Fixed for OWTable in #5164.

**Comment by irgolic** [comment]
Not fixed, it's still really slow with a big window.

Smaller window, higher FPS:
https://user-images.githubusercontent.com/24586651/104721396-654ec680-5725-11eb-8d35-f3b1fcb357f6.mov

Larger window, lower FPS:
https://user-images.githubusercontent.com/24586651/104721466-6aac1100-5725-11eb-8e3d-9ad5959cc04e.mov

This'll need a custom solution, I think it's slow because it queries the model for all the visible values on each repaint.
