### ISSUE TITLE
Missing windows name and icon

### ISSUE THREAD

**Issue by Dominiquini** [biolab/orange3#5383]
- [ ] **What's wrong?**

The 'Orange' window has neither a title nor an icon! 

![pythonw_prqMFKv5rn](https://user-images.githubusercontent.com/1180808/113498805-ab2a5800-94e6-11eb-93e0-7f98e5a70aa0.png)

- [ ] **How can we reproduce the problem?** 

1) Open Orange (run ''orange-canvas.exe" on terminal)
2) The opened windows doesn't have title or icon

- [ ] **What's your environment?**

- Operating system: Windows 10 x64
- Python version: 3.9.3 x64
- Orange version: 3.28.0
- How you installed Orange: Downloaded '.whl' of Orange from 'https://www.lfd.uci.edu/~gohlke/pythonlibs/#orange' and install with 'pip install ###.whl'

**Comment by markotoplak** [comment]
I confirm that the window title is empty on Ubuntu 20.04. When the workflow is saved, it is set to the workflow name. I agree that this is confusing. @irgolic, do you perhaps have any recommendation on how to name our windows, both "untitled" and the ones with workflows saved?

The icon works perfectly on my Linux machine. The reported problem could be a general windows problem (if our install scripts do not properly serve up icons for Windows) or maybe even an issue with the particular build? No idea.

**Comment by Dominiquini** [comment]
The title would be at least the name of the program - "Orange"!

**Comment by janezd** [comment]
@markotoplak, @ales-erjavec, this is fixed in https://github.com/biolab/orange-canvas-core/pull/189, right? If so, please close this issue.

**Comment by ales-erjavec** [comment]
Fixed by biolab/orange-canvas-core#189 and biolab/orange3#5375

**Comment by Dominiquini** [comment]
The icon is still missing:
![firefox_yqns1BRIho](https://user-images.githubusercontent.com/1180808/135670530-d77a62fe-7a2d-4d49-81de-57150f4ec9e0.png)
