### ISSUE TITLE
Plot axes not matching with graphs when copying to clipboard or saving as .png

### ISSUE THREAD

**Issue by AmewsSoft** [biolab/orange3#6543]
**What's wrong?**
When saving a distribution plot image as a .png file or copying it to the clipboard and pasting, the image axes do not align with the plot data. I've tested this on two PCs and experienced the same outcome. 

![image](https://github.com/biolab/orange3/assets/17097491/69c09713-2015-40ef-9502-8fffa9c90175)

**How can we reproduce the problem?** 
Zip file containing my .ows and data file: [A2.zip](https://github.com/biolab/orange3/files/12390452/A2.zip)

On a Windows PC, create a distribution plot and either go to Edit > Copy Image to Clipboard then paste it into another application such as Word, or save the distribution as a .png file and open that.

**What's your environment?**
- Operating system: Windows 11 Pro 10.0.22621 Build 22621
- Orange version: 3.35.0
- How you installed Orange: From the installer

**Comment by markotoplak** [comment]
Thanks. We've seen something similar multiple times: #5697 and #2887 (at least). But here we seem to be dealing with something new.

Could you inform us what is your screen resolution, size, and what the scaling setting is your system? Also, do you use multiple screens? If so, does the problem persist if you only have one screen connected?

**Comment by AmewsSoft** [comment]
No problem. I did see #5697 so already did a few tests to see if it might be that (hence why I also checked on my laptop since it only has a single screen). This looks to be a new issue though, as far as I can tell. 

My main setup has dual 1440p monitors at 144Hz, no scaling. My laptop has a single 2400x1600 screen, 150% scaling. Both exhibit the problem. Saving as an .svg or .pdf works ok, it's limited to copying or saving as .png.

**Comment by markotoplak** [comment]
Thanks for the info. @ZanMervic was able to reproduce the bug locally on his Windows laptop.

**Comment by PrimozGodec** [comment]
I think it is connected to https://github.com/pyqtgraph/pyqtgraph/issues/1250

**Comment by markotoplak** [comment]
I do not have a windows machine right now, but I suspect changes in biolab/orange-widget-base#208 or biolab/orange-widget-base#246.

If this is the only issue blocking the release, we could also ignore it for now.

**Comment by markotoplak** [comment]
This bug was introduced in biolab/orange-widget-base#246, which means widget-base 4.21.0 was problematic. And Orange 3.35.0 installers.

**Comment by markotoplak** [comment]
@AmewsSoft, @WolframRinke, this was just solved in orange-widget-base and will be available in orange-widget-base 4.22, which means with 3.36 official installers for most users.

Who installed manually will need to update orange-widget-base to 4.22, which will be available soon.

**Comment by WolframRinke** [comment]
Hi Marko,
thank you for this update, but it is still not matching the graph as shown in the widget, though it looks better. 😉

Kind regards,
Wolfram

[signature_2890823524]
Dipl.-Ing. Wolfram Rinke
Hochschullehrer | Senior Lecturer
Department Informationstechnologie | Information Technology
[Ein Bild, das Text, Grafiken, Grafikdesign, Screenshot enthält.  Automatisch generierte Beschreibung]
Fachhochschule Burgenland GmbH
Campus 1, 7000 Eisenstadt
T: +43 5 7705 4334
E: ***@***.***
W: www.fh-burgenland.at

UID: ATU 56954228 | Eisenstadt FN224782m
Follow us on TikTok Instagram Youtube LinkedIn Twitter | Like us on Facebook

Von: Marko Toplak ***@***.***>
Datum: Freitag, 15. September 2023 um 13:56
An: biolab/orange3 ***@***.***>
Cc: Rinke Wolfram ***@***.***>, Mention ***@***.***>
Betreff: Re: [biolab/orange3] Plot axes not matching with graphs when copying to clipboard or saving as .png (Issue #6543)

@AmewsSoft<https://github.com/AmewsSoft>, @WolframRinke<https://github.com/WolframRinke>, this was just solved in orange-widget-base and will be available in orange-widget-base 4.22, which means with 3.36 official installers for most users.

Who installed manually will need to update orange-widget-base to 4.22, which will be available soon.

**Comment by markotoplak** [comment]
@WolframRinke, thanks for testing. Could you show us differences in a screenshot?

**Comment by WolframRinke** [comment]
Hi Marko,

attached you will  find 3 screenshots showing this issue:

Picture 1 as shown in the widget:
[Ein Bild, das Screenshot, Text, Software, Zahl enthält.  Automatisch generierte Beschreibung]

Picture 2 as shown in the Report:
[Ein Bild, das Text, Software, Zahl, Computersymbol enthält.  Automatisch generierte Beschreibung]

Picture 3 as shown when saving as PNG file:
[Ein Bild, das Screenshot, Text, Diagramm, Zahl enthält.  Automatisch generierte Beschreibung]
Picture 4 what is shown as PDF:
[Ein Bild, das Software, Computersymbol, Multimedia-Software, Computer enthält.  Automatisch generierte Beschreibung]

I hope that helps.

Kind regards,
Wolfram

[signature_23353782]
Dipl.-Ing. Wolfram Rinke
Hochschullehrer | Senior Lecturer
Department Informationstechnologie | Information Technology
[Ein Bild, das Text, Grafiken, Grafikdesign, Screenshot enthält.  Automatisch generierte Beschreibung]
Fachhochschule Burgenland GmbH
Campus 1, 7000 Eisenstadt
T: +43 5 7705 4334
E: ***@***.***
W: www.fh-burgenland.at

UID: ATU 56954228 | Eisenstadt FN224782m
Follow us on TikTok Instagram Youtube LinkedIn Twitter | Like us on Facebook

Von: Marko Toplak ***@***.***>
Datum: Dienstag, 3. Oktober 2023 um 12:37
An: biolab/orange3 ***@***.***>
Cc: Rinke Wolfram ***@***.***>, Mention ***@***.***>
Betreff: Re: [biolab/orange3] Plot axes not matching with graphs when copying to clipboard or saving as .png (Issue #6543)

@WolframRinke<https://github.com/WolframRinke>, thanks for testing. Could you show us differences in a screenshot?

**Comment by WolframRinke** [comment]
Attached you will find the OWS file, that I used for the test plots.

Kind regards,
Wolfram


[signature_1532626600]
Dipl.-Ing. Wolfram Rinke
Hochschullehrer | Senior Lecturer
Department Informationstechnologie | Information Technology
[Ein Bild, das Text, Grafiken, Grafikdesign, Screenshot enthält.  Automatisch generierte Beschreibung]
Fachhochschule Burgenland GmbH
Campus 1, 7000 Eisenstadt
T: +43 5 7705 4334
E: ***@***.***
W: www.fh-burgenland.at

UID: ATU 56954228 | Eisenstadt FN224782m
Follow us on TikTok Instagram Youtube LinkedIn Twitter | Like us on Facebook

Von: Marko Toplak ***@***.***>
Datum: Dienstag, 3. Oktober 2023 um 12:37
An: biolab/orange3 ***@***.***>
Cc: Rinke Wolfram ***@***.***>, Mention ***@***.***>
Betreff: Re: [biolab/orange3] Plot axes not matching with graphs when copying to clipboard or saving as .png (Issue #6543)

@WolframRinke<https://github.com/WolframRinke>, thanks for testing. Could you show us differences in a screenshot?

**Comment by markotoplak** [comment]
@WolframRinke, thanks, but  it seems that if send images in an email, they do not get through. Could you please login into github and attach them here?

**Comment by WolframRinke** [comment]
You are right, sorry.
I put it in a PDF file. I will do it later on GitHUB.

Cheers, Wolfram


[signature_1815021747]
Dipl.-Ing. Wolfram Rinke
Hochschullehrer | Senior Lecturer
Department Informationstechnologie | Information Technology
[Ein Bild, das Text, Grafiken, Grafikdesign, Screenshot enthält.  Automatisch generierte Beschreibung]
Fachhochschule Burgenland GmbH
Campus 1, 7000 Eisenstadt
T: +43 5 7705 4334
E: ***@***.***
W: www.fh-burgenland.at

UID: ATU 56954228 | Eisenstadt FN224782m
Follow us on TikTok Instagram Youtube LinkedIn Twitter | Like us on Facebook

Von: Marko Toplak ***@***.***>
Datum: Dienstag, 3. Oktober 2023 um 15:30
An: biolab/orange3 ***@***.***>
Cc: Rinke Wolfram ***@***.***>, Mention ***@***.***>
Betreff: Re: [biolab/orange3] Plot axes not matching with graphs when copying to clipboard or saving as .png (Issue #6543)

@WolframRinke<https://github.com/WolframRinke>, thanks, but it seems that if send images in an email, they do not get through. Could you please login into github and attach them here?

**Comment by WolframRinke** [comment]
[orange3_plotting_issue.pdf](https://github.com/biolab/orange3/files/12818404/orange3_plotting_issue.pdf)
[orange_plot_test.ows.zip](https://github.com/biolab/orange3/files/12818407/orange_plot_test.ows.zip)

here are the missing files.

**Comment by markotoplak** [comment]
Thanks, yes, I confirm the problem. Could you show me which packages do you have? Can you open Orange command prompt (there is an icon in the start menu for it) and type `pip freeze` and then paste the output here.
